# Generated by Django 4.2.6 on 2023-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
