# Generated by Django 4.2.6 on 2023-11-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_url_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('neighborhood', models.CharField(max_length=255)),
                ('house_numer', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('complement', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('reference', models.CharField(max_length=255, null=True)),
                ('uf', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
