# Generated by Django 4.2.6 on 2023-11-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='house_numer',
            new_name='house_number',
        ),
    ]
