# Generated by Django 4.2.6 on 2023-11-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_house_numer_adress_house_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
