# Generated by Django 4.2.6 on 2023-12-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_receiver_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TR', 'Transfer'), ('WD', 'Withdraw'), ('DP', 'Deposit'), ('CR', 'Credit'), ('LN', 'Loan')], default='TR', max_length=2),
            preserve_default=False,
        ),
    ]
