# Generated by Django 4.2.6 on 2023-11-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_loginattempt_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='ip',
        ),
    ]
