# Generated by Django 4.2.6 on 2023-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_loginattempt_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='ip',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
