# Generated by Django 4.2.6 on 2023-12-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loan_loaninstallments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaninstallments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='core.loan'),
        ),
    ]
