# Generated by Django 4.2.6 on 2023-12-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_creditcard_transaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.IntegerField(default=1),
        ),
    ]
