# Generated by Django 4.2.6 on 2023-12-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_transaction_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_date', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.creditcard')),
            ],
        ),
    ]
