# Generated by Django 4.2.6 on 2023-12-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_creditinstallments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditinstallments',
            old_name='creditId',
            new_name='creditCard',
        ),
        migrations.AddField(
            model_name='creditinstallments',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='core.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='core.account'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=16),
        ),
    ]
